# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: levy's page
name: Lucas de Levy Oliveira
email: lucasdelevy@gmail.com
original_url: "http://lucasdelevy.com"
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page!
  I'm currently moving from Amazon AWS + Wordpress, so it's not fully setup yet. :-)
  You can check the original website at <a href="http://lucasdelevy.com">lucasdelevy.com</a>
baseurl: "/welcome" # the subpath of your site, e.g. /blog
url: "lucasdelevy.com" # the base hostname & protocol for your site
facebook_username: lucasdelevy
github_username:  lucasdelevy
linkedin_username: lucasdelevy

# Build settings
markdown: kramdown
