# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: levy's playground
name: Lucas de Levy Oliveira
email: lucasdelevy@neuron.eei.eng.osaka-u.ac.jp
original_url: "http://lucasdelevy.com"
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page! It is surely not yet complete, but I'll be adding information soon enough. :-)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lucasdelevy.com" # the base hostname & protocol for your site
facebook_username: lucasdelevy
github_username:  lucasdelevy
linkedin_username: lucasdelevy

# Build settings
markdown: kramdown

gems:
- jekyll-email-protect
